# Generated by Django 5.0.1 on 2024-02-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='Phone',
        ),
    ]
