# Generated by Django 5.0.1 on 2024-02-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_address_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='NIC',
            field=models.CharField(default='', max_length=12),
        ),
    ]
