# Generated by Django 5.0.1 on 2024-02-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='NIC',
            field=models.CharField(max_length=12),
        ),
    ]
